### PR TITLE
Fixes supporting vcdat

### PR DESCRIPTION
**Pull request by scottwittenburg**

### CODE REVIEW

**Comment by scottwittenburg** [comment]
@James-Crean We could always merge this and get at least the first couple things you need merged.  I was going to wait until we had a solution for #41 (waiting on @doutriaux1 for some more information there), but there's really no need to do it all in one topic.

As it stands, this addresses #38, as well as the `modulo` stuff we talked about yesterday.  Let me know if it seems like it will do the job.

**Comment by James-Crean** [comment]
LGTM. Once that is merged I can work on the vCDAT features that use them. If i run into anything else that I need I will let you know. 

As for #41, I agree on submitting these separately. No need to clump all the features into one PR.

**Comment by scottwittenburg** [comment]
@danlipsa or @doutriaux1 I guess one of you may need to merge this, as I don't seem to have write access to this repo.

**Comment by scottwittenburg** [comment]
You're right @doutriaux1, that name does seem to make more sense.  Before @James-Crean starts depending on the wrong name, I'll push a quick fix...

**Pull request merged**
