### PR TITLE
fixes issues with drs files, cannot open the file twice at same time,…

### PR DESCRIPTION
**Pull request by doutriaux1**
… we need to close it before re-opening it somewhere else, so the cache had to be somehow undone here...

### CODE REVIEW

**Comment by doutriaux1** [comment]
@scottwittenburg should I worry about travis failure?

**Comment by scottwittenburg** [comment]
I guess I would worry a bit, since the test that is failing is related to getting variable information for a variable from a file, which seems to be related to the change.  Let me know if you want me to look into, or if you want to chat briefly about the best way to debug it.

**Comment by doutriaux1** [comment]
@scottwittenburg how do i run the tests locally?

**Comment by scottwittenburg** [comment]
It's been awhile since I set that stuff up, but IIRC, just `npm run test` should do it.  I think you just need to have activated an environment where all the deps are available.

**Comment by doutriaux1** [comment]
@downiec @scottwittenburg @danlipsa ok i fixed the test suite. Ready to review and merge.

**Comment by doutriaux1** [comment]
@scottwittenburg let's wait for these changes to see if i didn't break anything
made the code py3 compatible, we will need this for vcdat 2.0 anyway

**Pull request merged**
